pipeline {
    agent any

    tools {
        maven 'Maven 4.0.0'      // Use your Maven installation name from Jenkins
        jdk 'JDK 21'             // Use your JDK installation name from Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/suvajitall/FLPKRT_0_1.git' // Your Git repo
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/**/*.png', fingerprint: true
            junit 'target/surefire-reports/*.xml'
        }
    }
}
